name: network
help: Network Helper Scripts
alias: net
examples: 
  - st network interfaces
  - st net ifs
  - st network speedtest
  - st net st
  - st network publicip
  - st net pip
  - st network localip
  - st net lip
  - st network wifiinfo
  - st net wifi
commands:
  - name: interfaces
    alias: ifs
    examples: 
      - st network interfaces
      - st net ifs
    help: Show network interfaces
  - name: linkspeed
    alias: speed
    examples:
      - st network linkspeed
      - st net speed
    help: Show link speed of network interfaces
  - name: speedtest
    alias: st
    examples:
      - st network speedtest
      - st net st
    help: Run a network speed test
  - name: publicip
    alias: pip
    examples:
      - st network publicip
      - st net pip
    help: Show public IP address
  - name: localip
    alias: lip
    examples:
      - st network localip
      - st net lip
    help: Show local IP address
  - name: wifiinfo
    alias: wifi
    examples:
      - st network wifiinfo
      - st net wifi
    help: Show Wi-Fi information