name: rclone
alias: rc
help: Rclone Related Utilities
commands:
  - name: dry-sync
    alias: ds
    help: Perform a dry run of rclone sync
    examples:
      -  st rclone dry-sync source destination
      -  st rc dry-sync source destination  
    args:
      - name: source
        required: true
        unique: false
      - name: destination
        required: true
        unique: false
  - name: sync
    alias: s
    help: Perform rclone sync
    args:
      - name: source
        required: true
        unique: false
      - name: destination
        required: true
        unique: false