name: rclone
alias: rc
help: Rclone Related Utilities
examples:
  - st rclone dry-sync source destination
  - st rc dry-sync source destination
  - st rclone sync source destination
  - st rc sync source destination
commands:
  - name: dry-sync
    alias: ds
    help: Perform a dry run of rclone sync
    examples:
      -  st rclone dry-sync source destination
      -  st rc dry-sync source destination  
    args:
      - name: source
        required: true
        unique: false
      - name: destination
        required: true
        unique: false
  - name: sync
    alias: s
    help: Perform rclone sync
    examples:
      -  st rclone sync source destination
      -  st rc sync source destination
    args:
      - name: source
        required: true
        unique: false
      - name: destination
        required: true
        unique: false
  - name: copy
    alias: c
    help: Perform rclone copy
    examples:
      -  st rclone copy source destination
      -  st rc copy source destination
    args:
      - name: source
        required: true
        unique: false
      - name: destination
        required: true
        unique: false