name: resticprofile
alias: rp
help: Restic Profile Management
commands:
  - name: show
    alias: s
    help: Show Restic Profile Details
    examples:
      - st resticprofile show myprofile
      - st rp s myprofile

  - name: list
    alias: ls
    help: List All Restic Profiles
    examples:
      - st resticprofile list
      - st rp ls

  - name: snapshots
    alias: ss
    help: List Snapshots in Restic Profile
    args:
      - name: profile
        help: Name of the Restic Profile
    flags:
      - long: --compact
        short: -c
        help: Display snapshots in compact format
    examples:
      - st resticprofile snapshots myprofile
      - st rp ss myprofile

  - name: backup
    alias: b
    help: Perform Backup with Restic Profile
    args:
      - name: profile
        help: Name of the Restic Profile
    flags:
      - long: --dry-run
        short: -d
        help: Perform a dry run without actual backup
    examples:
      - st resticprofile backup myprofile
      - st rp b myprofile --dry-run