name: system
alias: sys
help: System Related Utilities
commands:
  - name: update
    help: Update System Packages
    alias: upd

  - name: upgrade
    help: Upgrade System Packages
    alias: upg

  - name: update-upgrade
    help: Update & Upgrade System Packages
    alias: updu

  - name: info
    help: Show system info

  - name: smart
    help: Show SSD SMART stats
    flags:
      - long: --full
        help: Show full SMART stats

  - name: disk
    help: Show disk usage stats

  - name: install
    help: Install Packages
    alias: i
    examples:
      - st sys install all
      - st sys i all
      - st sys install docker
      - st sys i docker
      - st sys install btop
      - st sys i btop
    commands:
      - name: all
        help: Install all packages
      - name: docker
        help: Install Docker
      - name: btop
        help: Install btop
      - name: eza
        help: Install eza
      - name: neofetch
        help: Install neofetch
      - name: ncdu
        help: Install ncdu
      - name: duf
        help: Install duf
      - name: vnstat
        help: Install vnstat
      - name: ufw
        help: Install ufw
      - name: bat
        help: Install bat
      - name: rclone
        help: Install rclone
      - name: restic
        help: Install restic
      - name: resticprofile
        help: Install restic profile
      - name: tmux
        help: Install tmux
  - name: uninstall
    help: Uninstall Packages
    alias: un
    examples:
      - st sys uninstall all
      - st sys un all
      - st sys uninstall docker
      - st sys un docker
      - st sys uninstall btop
      - st sys un btop
    commands:
      - name: all
        help: Uninstall all packages
      - name: docker
        help: Uninstall Docker
      - name: btop
        help: Uninstall btop
      - name: eza
        help: Uninstall eza
      - name: neofetch
        help: Uninstall neofetch
      - name: ncdu
        help: Uninstall ncdu
      - name: duf
        help: Uninstall duf
      - name: vnstat
        help: Uninstall vnstat
      - name: ufw
        help: Uninstall ufw
      - name: bat
        help: Uninstall bat
      - name: rclone
        help: Uninstall rclone
      - name: restic
        help: Uninstall restic
      - name: resticprofile
        help: Uninstall restic profile
      - name: tmux
        help: Uninstall tmux
