name: system
alias: sys
help: System Related Utilities
commands:
  - name: update
    help: Update System Packages
    alias: upd

  - name: upgrade
    help: Upgrade System Packages
    alias: upg

  - name: update-upgrade
    help: Update & Upgrade System Packages
    alias: updu

  - name: info
    help: Show system info
    flags:
      - long: --full
        help: Show full system info

  - name: smart
    help: Show SSD SMART stats
    flags:
      - long: --full
        help: Show full SMART stats

  - name: disk
    help: Show disk usage stats

  - name: audit
    help: Run self audit to check for issues
    alias: au