st system install vnstat
st system install docker
st system install btop
st system install eza
st system install ncdu
st system install duf
st system install ufw
st system install bat
st system install resticprofile
st system install rclone
st system install restic