st system uninstall vnstat
st system uninstall docker
st system uninstall btop
st system uninstall eza
st system uninstall ncdu
st system uninstall duf
st system uninstall ufw
st system uninstall bat
st system uninstall resticprofile
st system uninstall rclone
st system uninstall restic